// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlSubPLMbeN7UQevlrwQRdHUSZRpHb2e0',
    appId: '1:701749616587:web:3df78dd9d6a2cef611e04e',
    messagingSenderId: '701749616587',
    projectId: 'ballouchi-23808',
    authDomain: 'ballouchi-23808.firebaseapp.com',
    storageBucket: 'ballouchi-23808.firebasestorage.app',
    measurementId: 'G-C9SNQJP5YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZSsBavsxmGZteGrSKmRjJHl2jU_sdWXg',
    appId: '1:701749616587:android:2bf75012ed9eaf0a11e04e',
    messagingSenderId: '701749616587',
    projectId: 'ballouchi-23808',
    storageBucket: 'ballouchi-23808.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAhU4Sy4k-b9x0FIyX5nGISvGvt59J-H0',
    appId: '1:701749616587:ios:20a66aba66e6011a11e04e',
    messagingSenderId: '701749616587',
    projectId: 'ballouchi-23808',
    storageBucket: 'ballouchi-23808.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAhU4Sy4k-b9x0FIyX5nGISvGvt59J-H0',
    appId: '1:701749616587:ios:20a66aba66e6011a11e04e',
    messagingSenderId: '701749616587',
    projectId: 'ballouchi-23808',
    storageBucket: 'ballouchi-23808.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlSubPLMbeN7UQevlrwQRdHUSZRpHb2e0',
    appId: '1:701749616587:web:480aaa5da45f0b2911e04e',
    messagingSenderId: '701749616587',
    projectId: 'ballouchi-23808',
    authDomain: 'ballouchi-23808.firebaseapp.com',
    storageBucket: 'ballouchi-23808.firebasestorage.app',
    measurementId: 'G-4FX2EZ5YGW',
  );
}
